### PR TITLE
Rename Keys.key_type to Keys.type (#459)

### LINKED ISSUE #459: Rename Keys.key_type to Keys.type
Seems cleaner to do this instead of saying key again.

### PR DESCRIPTION
**Pull request by DreamN**
Closes #459 
@ColdHeat

### CODE REVIEW

**Comment by ColdHeat** [comment]
Mmmm not quite... You can't just rename all instances of key_type because if there are existing CTFd instances that update they will be running outdated schemas. 

Instead you need to rename all instances only within the `CTFd` & `tests` folders and then create a migration for [Flask-Migrate](https://flask-migrate.readthedocs.io/en/latest/)

**Comment by DreamN** [comment]
@ColdHeat Fixed :D

**Comment by DreamN** [comment]
Fixed @ColdHeat

**Comment by ColdHeat** [comment]
Yes I can see that. Please be patient. This issue is slated for v1.1 so it will get merged into that when the time is right.

**Comment by DreamN** [comment]
Awesome, Thank you 😄 
That's my very first pull request in github. 🍻

**Pull request merged**
