### PR TITLE
bump flake8 to 3.8.2, fix F523 violations

### PR DESCRIPTION
**Pull request by ldruschk**
This pull request resolves the following failing checks which were introduced in pyflakes 2.2

```
CTFd/views.py:139:21: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_challenges.py:211:25: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_challenges.py:234:29: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_challenges.py:310:25: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_scoreboard.py:250:30: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_scoreboard.py:253:30: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_scoreboard.py:263:30: F523 '...'.format(...) has unused arguments at position(s): 0
tests/users/test_scoreboard.py:273:30: F523 '...'.format(...) has unused arguments at position(s): 0
```

### CODE REVIEW

**Comment by ldruschk** [comment]
Apparently the flake8-isort checks weren't being run at all before this update. When removing the ignore for I002 in the old version it complains about e.g.:
```
tests/teams/test_scoreboard.py:0:1: I002 no configuration found (.isort.cfg or [isort] in configs)
```
which now leads to
```
tests/teams/test_scoreboard.py:5:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:6:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:7:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:8:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:9:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:10:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:11:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:12:1: I001 isort found an import in the wrong position
tests/teams/test_scoreboard.py:13:1: I001 isort found an import in the wrong position
```
I don't believe this was intentional?

**Comment by ColdHeat** [comment]
¯\\\_(ツ)\_/¯

You're welcome to fix the failing lints as well. Updating dependencies has a tendency to do things like that.

**Comment by ldruschk** [comment]
The `.isort.cfg` includes the "black-compatible" settings as described here: https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort

**Comment by ColdHeat** [comment]
I'm merging this in and will fix the lints up in my branch. Thanks for the great PR!

**Pull request merged**
