### PR TITLE
#2623 Fix saving bracket bug.

### LINKED ISSUE #2623: Saving new bracket few times creates new instances of the same bracket
**Environment**:

- CTFd Version/Commit: latest
- Operating System: Linux Debian 12
- Web Browser and Version: Firefox 130.0b6 (64-bit)

**What happened?**
Creating new bracket and clicking save several times adds new bracket each time instead of patching the existing one. 

**What did you expect to happen?**
It should save one bracket and then update it.

**How to reproduce your issue**
Steps to reproduce:

1. Go to admin->config
2. Go to Scoreboard brackets
3. Click Add New Bracket
4. Fill the form
5. Click Save several  times - each time you click the bracket is saved as new. 

**Any associated stack traces or error logs**
There is a bug in code right here:

https://github.com/CTFd/CTFd/blob/0d12a13d6a39d5b9dc21c5efd4e29c4ca05e6128/CTFd/themes/admin/assets/js/components/configs/brackets/Bracket.vue#L115

Seems like a copy-paste bug. It should be this.bracket = response.data; 

I have created a fix and will send a PR soon.

### PR DESCRIPTION
**Pull request by br0xpl**
Fixes #2623

### CODE REVIEW

**Comment by br0xpl** [comment]
I had to update the plugin @vitejs/plugin-vue version and recompile statics... Hope this will not break any other part?

**Comment by ColdHeat** [comment]
PR is missing source code change?

**Comment by br0xpl** [comment]
@ColdHeat : There are 24 files changed?

It is a bug in the admin theme itself.
image

**Comment by ColdHeat** [comment]
image

The files you commited are all compiled assets. You need to edit the source file not the compiled assets.

**Comment by br0xpl** [comment]
@ColdHeat  sorry indeed something went wrong with the cleaning up. I will file a new PR. Sorry.

**Pull request closed without merging**
