### PR TITLE
Add length error content that is too long

### PR DESCRIPTION
**Pull request by ColdHeat**
* Add length checking to some sensitive fields in Pages and Challenges.
* Works on #1786

This is enough to fix most of the issues but this is really a systemic problem for most of the API endpoints. We should have something that verifies data consistency. Marshmallow is not good enough at this. Pydantic seems like it would be superior here.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Merging this even without full test coverage because there shouldn't be any kind of break in functionality. Although thinking about it there should be a few tests but I think I will leave that for a more systemic solution.

**Comment by frankli0324** [comment]
There **is** length validation in marshmallow

https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html?highlight=validate.Length#marshmallow.validate.Length

**Comment by ColdHeat** [comment]
I believe that would require adding the field explicitly in the schema instead of relying on the model.

**Comment by frankli0324** [comment]
you are not relying on the model anyway...😓

**Comment by frankli0324** [comment]
Could be combined with https://stackoverflow.com/questions/1777814/how-to-get-sqlalchemy-length-of-a-string-column

**Comment by frankli0324** [comment]
image
this is ur User schema

and maybe you are looking for ma.SQLAlchemyAutoSchema

**Comment by frankli0324** [comment]
https://github.com/frankli0324/CTFd/commit/16d8f1c27c302717c3653b402f9478369e95d610

at least for the sake of code consistency

**Comment by ColdHeat** [comment]
Ah okay, I apologize. I misunderstood what you meant but if I was honest I don't like Marshmallow and the code will eventually be removed. 

If you'd like you can PR the field based solution.

**Pull request merged**
