### PR TITLE
Update dynamic_challenges plugin ui to disable modification of current_value items

### PR DESCRIPTION
**Pull request by invom**
Fix wrong quotes for base.html

### CODE REVIEW

**Comment by ColdHeat** [comment]
Is there any light HTML linting that could be done here on the HTML files? There's got to be a way to fix all these problems wholesale?

**Comment by invom** [comment]
I found this https://github.com/htmlhint/HTMLHint and I will review all the pages later if needed.

**Comment by ColdHeat** [comment]
Hi @invom, I'll go ahead and merge this since I don't see any problems with it and it solves a UI issue. Regarding your linting issues, it would be great if you could work on integrating an HTML/Jinja linter into the testing process.

**Comment by invom** [comment]
I will try to do it during the holiday .

**Pull request merged**
