### PR TITLE
Vagrant Ubuntu 18.04

### PR DESCRIPTION
**Pull request by muttiopenbts**
Changed vagrant base box image to Ubuntu 18.04.
18.10 might not be reliable enough.

### CODE REVIEW

**Comment by ColdHeat** [comment]
> # BOX_IMG = "ubuntu/bionic64" # psycopg2 problem

Hmm I think I've also run into a psycopg2 installation issue but I suspect it can be avoided by removing that dependency and relying on `psycopg2-binary`. I'll make that change in master shortly.

**Comment by ColdHeat** [comment]
See #1720. I rebased your PR on master. I suspect `ubuntu/bionic64` will work now.

**Comment by ColdHeat** [comment]
Just so you know you can create a branch and then PR against that branch so you don't have to keep deleting PRs and recreating them. This looks like a good tutorial: https://opensource.com/article/19/7/create-pull-request-github

**Comment by muttiopenbts** [comment]
Having trouble ssh. ssh pubkey authc fails.

**Pull request closed without merging**
