### PR TITLE
Gender-neutral alternative

### PR DESCRIPTION
**Pull request by ldionmarcil**
Gender-neutralism is good practice. Diversity etc.

### CODE REVIEW

**Comment by tjgerot** [comment]
As seemingly trivial as it may be, it deserves a merge.

**Comment by Owlz** [comment]
For reference, this should be "his or her". "Their" is a plural while the rest of the sentence is not.

**Comment by rkkautsar** [comment]
@Owlz see [Singular they](https://en.wikipedia.org/wiki/Singular_they)

**Comment by ColdHeat** [comment]
It was a [CSAW CTF](https://csaw.engineering.nyu.edu/ctf) challenge at some point to submit a PR to CTFd. This solved the challenge but the comment it referred to no longer exists so I'm going to close this.

**Pull request closed without merging**
