### PR TITLE
Questions about optimizing Dockerfile play

### PR DESCRIPTION
**Pull request by 99Kies**
## optimize Dockerfile, make the container lighter, mainly by removing PIP and apk download file cache to achieve a goal

**Environment**:

  - CTFd Version/Commit:
  - Operating System:
  - Web Browser and Version:

**What happened?**

**What did you expect to happen?**

Let the container lighter!

**How to reproduce your issue**

**Any associated stack traces or error logs**
-----------------
I feel sorry about my English

### CODE REVIEW

**Comment by ColdHeat** [comment]
Looks like a reasonable change. I'll need to do a quick comparison to see exactly what the size benefits are. I'll also have to carry this forward when we move to debian.

**Comment by 99Kies** [comment]
> Looks like a reasonable change. I'll need to do a quick comparison to see exactly what the size benefits are. I'll also have to carry this forward when we move to debian.

I think the alpine than debian/ubuntu and lighter, more suitable for the construction of the python web services, what do you think?

**Comment by 99Kies** [comment]
I often use alpine as the flask deployed docker image, hahaha

**Comment by ColdHeat** [comment]
This is summarized here: #1215 

Alpine is probably smaller but it leads to other odd issues like random performance losses. You also can't download wheels from pypi which makes builds slow and hard to cache. In general it just sucks.

**Comment by 99Kies** [comment]
Sorry, I only focus on the container size, I got it. So the future plan to put the docker image replacement for debian?

**Comment by ColdHeat** [comment]
Yes the future Docker base image will be Debian. It would've been done sooner but making a big change like that needs to be done in a major release. People can still use a custom Debian base image if they want the benefits though. 

Regarding this PR it looks like there's a very slight size savings:
```
ctfd/ctfd                                                   latest                         ad31929b2012        56 minutes ago      532MB
ctfd-branch                                                 latest                         367c115bb36c        5 minutes ago       497MB
```

Seems worth it overall though.

**Pull request merged**
