### PR TITLE
Define additional python 2 libraries to fix vagrant up #1345

### LINKED ISSUE #1345: vagrant up fails due to newer version of setuptools and banal
**Environment**:

  - CTFd Version/Commit: 05e5730c54355a3056f82f7ac38a864af5270ffd
  - Operating System: Ubuntu 19.10 x64
  - Web Browser and Version: Firefox 75.0 (64-bit)

**What happened?**
`vagrant up` fails to launch flask app due to python library dependency

**What did you expect to happen?**
vagrant to stage ctfd

**How to reproduce your issue**
vagrant up

**Any associated stack traces or error logs**
python serve.py
```
Traceback (most recent call last):
  File "serve.py", line 1, in <module>
    from CTFd import create_app
  File "/vagrant/CTFd/__init__.py", line 7, in <module>
    from flask import Flask, Request
ImportError: No module named flask
```
pip install -r requirements.txt
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: zipp>=0.5 .dist-info directory not found
```

### PR DESCRIPTION
**Pull request by tommychinjr**
Specified version of setuptools and banal to fix vagrant up to work with python 2

fixes #1345

### CODE REVIEW

**Comment by ColdHeat** [comment]
Is `setuptools` really required here?

**Comment by tommychinjr** [comment]
> Is `setuptools` really required here?
Yes--the build script uses the latest version of setuptools and version 45+ causes problems so I defined the version (last release prior to version 45) to satisfy the python 2 requirement. 

Below is the error message without defining setuptools version:

```
pip install -r requirements.txt 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting banal==0.4.2
  Using cached banal-0.4.2-py2.py3-none-any.whl (5.0 kB)
Collecting Flask==1.1.1
  Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)
Collecting Werkzeug==0.16.0
  Using cached Werkzeug-0.16.0-py2.py3-none-any.whl (327 kB)
Collecting Flask-SQLAlchemy==2.4.1
  Using cached Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl (17 kB)
Collecting Flask-Caching==1.4.0
  Using cached Flask_Caching-1.4.0-py2.py3-none-any.whl (16 kB)
Collecting Flask-Migrate==2.5.2
  Using cached Flask_Migrate-2.5.2-py2.py3-none-any.whl (13 kB)
Collecting Flask-Script==2.0.6
  Using cached Flask-Script-2.0.6.tar.gz (43 kB)
Collecting SQLAlchemy==1.3.11
  Using cached SQLAlchemy-1.3.11.tar.gz (6.0 MB)
Collecting SQLAlchemy-Utils==0.36.0
  Using cached SQLAlchemy-Utils-0.36.0.tar.gz (127 kB)
Collecting passlib==1.7.2
  Using cached passlib-1.7.2-py2.py3-none-any.whl (507 kB)
Collecting bcrypt==3.1.7
  Using cached bcrypt-3.1.7-cp27-cp27mu-manylinux1_x86_64.whl (59 kB)
Collecting six==1.13.0
  Using cached six-1.13.0-py2.py3-none-any.whl (10 kB)
Collecting itsdangerous==1.1.0
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting requests>=2.20.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting PyMySQL==0.9.3
  Using cached PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
Collecting gunicorn==19.9.0
  Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Collecting normality==2.0.0
  Using cached normality-2.0.0-py2.py3-none-any.whl (10 kB)
Collecting dataset==1.1.2
  Using cached dataset-1.1.2-py2.py3-none-any.whl (14 kB)
Collecting mistune==0.8.4
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting netaddr==0.7.19
  Using cached netaddr-0.7.19-py2.py3-none-any.whl (1.6 MB)
Collecting redis==3.3.11
  Using cached redis-3.3.11-py2.py3-none-any.whl (66 kB)
Collecting datafreeze==0.1.0
  Using cached datafreeze-0.1.0-py2.py3-none-any.whl (13 kB)
Collecting gevent==1.4.0
  Using cached gevent-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl (5.0 MB)
Collecting python-dotenv==0.10.3
  Using cached python_dotenv-0.10.3-py2.py3-none-any.whl (16 kB)
Collecting flask-restplus==0.13.0
  Using cached flask_restplus-0.13.0-py2.py3-none-any.whl (2.5 MB)
Collecting pathlib2==2.3.5
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting flask-marshmallow==0.10.1
  Using cached flask_marshmallow-0.10.1-py2.py3-none-any.whl (9.7 kB)
Collecting marshmallow-sqlalchemy==0.17.0
  Using cached marshmallow_sqlalchemy-0.17.0-py2.py3-none-any.whl (13 kB)
Collecting boto3==1.10.39
  Using cached boto3-1.10.39-py2.py3-none-any.whl (128 kB)
Collecting marshmallow==2.20.2
  Using cached marshmallow-2.20.2-py2.py3-none-any.whl (50 kB)
Collecting click>=5.1
  Using cached click-7.1.1-py2.py3-none-any.whl (82 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting alembic>=0.7
  Using cached alembic-1.4.2.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.1
  Using cached cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (387 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting text-unidecode
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Processing /home/vagrant/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd/PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython"
  Using cached greenlet-0.4.15-cp27-cp27mu-manylinux1_x86_64.whl (39 kB)
Collecting typing; python_version < "3.5"
  Using cached typing-3.7.4.1-py2-none-any.whl (26 kB)
Collecting jsonschema
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting enum34; python_version < "3.4"
  Using cached enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting aniso8601>=0.82
  Using cached aniso8601-8.0.0-py2.py3-none-any.whl (43 kB)
Collecting pytz
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Processing /home/vagrant/.cache/pip/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335/scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl
Collecting s3transfer<0.3.0,>=0.2.0
  Using cached s3transfer-0.2.1-py2.py3-none-any.whl (70 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.9.5-py2.py3-none-any.whl (24 kB)
Collecting botocore<1.14.0,>=1.13.39
  Using cached botocore-1.13.50-py2.py3-none-any.whl (5.9 MB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting python-editor>=0.3
  Using cached python_editor-1.0.4-py2-none-any.whl (4.9 kB)
Collecting Mako
  Using cached Mako-1.1.2-py2.py3-none-any.whl (75 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Processing /home/vagrant/.cache/pip/wheels/b5/18/32/77a1030457155606ba5e3ec3a8a57132b1a04b1c4f765177b2/functools32-3.2.3.post2-cp27-none-any.whl
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: setuptools in /home/vagrant/.virtualenvs/ctfd/lib/python2.7/site-packages (from jsonschema->flask-restplus==0.13.0->-r requirements.txt (line 25)) (45.0.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'
```

**Comment by ColdHeat** [comment]
Even so pinning setuptools seems unnecessary. I think a better solution would be to move to Python 3 in the Vagrantfile.

**Comment by ColdHeat** [comment]
Hi I generally try to let the Vagrantfile be community supported. Do you think you have the time to update it to Python 3 instead of Python 2?

**Comment by tommychinjr** [comment]
> Hi I generally try to let the Vagrantfile be community supported. Do you think you have the time to update it to Python 3 instead of Python 2?

That'll actually be much easier to work with since I had the system working in python3 but kept versioning in python 2 to match everything else. I'll send a pull when I get around to it

**Pull request closed without merging**
