### PR TITLE
Update french translations

### LINKED ISSUE #2642: French translation of "place"
**Environment**:

- CTFd Version/Commit: 3.7.4
- Operating System: NA
- Web Browser and Version: NA

**What happened?**

The french translation of CTFd I did months ago contains a mis-translated "place".

**What did you expect to happen?**

In the given context of use, "place" is used as "rank" and not as a geographic position.

I pushed an issued on Crowdin, I open this one for traceability.

**How to reproduce your issue**

Run CTFd, change language to French.

**Any associated stack traces or error logs**

### PR DESCRIPTION
**Pull request by adam-lebon**
Request for review from French people before deleting the draft label
cc @erdnaxe @pandatix 

Fixes #2642

### CODE REVIEW

**Comment by pandatix** [comment]
Shouldn't it be fixed on Crowdin directly ? I think I submitted fixes weeks ago that did not receive a review :/

**Comment by adam-lebon** [comment]
I searched, and I didn't find any way to join the crowdin platform :/

**Comment by pandatix** [comment]
Here: https://crowdin.com/project/CTFd

**Comment by adam-lebon** [comment]
Translations has been updated on crowdin

**Comment by erdnaxe** [comment]
> Translations has been updated on crowdin

Thank you!

**Pull request closed without merging**
