### PR TITLE
Extension that allows to restrict the allowed users to configured domains or emails

### PR DESCRIPTION
**Pull request by pedromigueladao**
This extension allows the admin to configure a set of domains and usernames such that only users from these domains (or those addresses explicitly specified) can register.
Invalid e-mails and domains are silently discarded.

### CODE REVIEW

**Comment by pedromigueladao** [comment]
resolves #441 resolves #603

**Comment by ColdHeat** [comment]
Hi @pedromigueladao. Thanks for putting in the time to write this and get tests working! I think this is better suited as a plugin to CTFd instead of a core feature at the moment. 

Also development is happening in the 2.0.0 branch so any major features should go there.

**Comment by pedromigueladao** [comment]
Thanks @ColdHeat . I will need this for a course that I am going to teach this fall so I was developing over the current stable version.
Is any major difference between 2.0.0 and the current one? (to measure the effort taken to develop for that version)

**Comment by pedromigueladao** [comment]
Also @ColdHeat  I see it available in the ctfd.io. Will you make it available for 2.0.0 (by default or as a plugin)?

**Comment by ColdHeat** [comment]
@pedromigueladao 2.0.0 is a very large rewrite. It's likely that your plugin will break in 2.0.0. I would wait until it is stabilized and then try to develop it. 

However the current version works just fine so I don't think there's much issue with simply targeting 1.2.0 and then updating later. 

As for future versions yes email whitelisting is listed as part of 2.0.0. https://github.com/CTFd/CTFd/issues/603

**Comment by ColdHeat** [comment]
2.0.0 now has whitelisting email domains built in so I'm going to close this.

**Pull request closed without merging**
