### PR TITLE
Fixed german translations

### PR DESCRIPTION
**Pull request by xXLeoXxOne**
Many of the german translations were wrong or missing so I spent some time (re-)translating all of them.

Additionally, I have removed the "fuzzy" keywords so that all translations show up on the website.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Thanks for this! I was hoping to keep all the translations in the online service at POEditor: https://docs.ctfd.io/docs/contributing/overview#translations. But I'll see if I can possibly merge this together with that.

**Comment by xXLeoXxOne** [comment]
Oh sorry, I kinda forgot to look that up before changing it manually. Kinda new to this and just wanted a proper translation for my small own event.
If needed, I can manually transfer it to that editor.

**Comment by ColdHeat** [comment]
@xXLeoXxOne I'm going to approve you on POEditor under the email with the same username as your Github one. But if you want it on a different account just let me know. 

I will have to figure out how to sync changes back and forth but right now the POEditor set of changes is better since another German speaker already went through it. But if you can go through it one more time I can sync the changes to Github.

**Comment by xXLeoXxOne** [comment]
Went through everything again and added some of my changes so that every translation looks perfect to me.

**Comment by ColdHeat** [comment]
I copied over the PO file from POEditor and pushed it to your fork so that you get the git commit credit. Thanks for the help translating!

**Pull request merged**
