### PR TITLE
Slim down the size of docker image

### PR DESCRIPTION
**Pull request by khiemdoan**
`python3-dev` is already included in `python:3.7-slim-buster`. So we don't need to install it again.
This helps us reduce more than 100MB.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Is this actually the case? https://github.com/docker-library/python/blob/master/3.7/buster/slim/Dockerfile

CTFd in some cases needs to be able to install requirements at runtime so I'm not sure it's safe to remove this just yet.

**Comment by khiemdoan** [comment]
I have tested with some packages that require it, such as mysqlclient, psycopg2, python-Levenshtein. They can still be installed without any problem.

```
FROM python:3.7-slim-buster

RUN apt-get update -y && apt-get install -y --no-install-recommends gcc libpq-dev libmariadb-dev

RUN pip3 install mysqlclient
RUN pip3 install psycopg2
RUN pip3 install python-Levenshtein
```

**Comment by ColdHeat** [comment]
Okay I think this may have some weight. I will need to test it more and I'm traveling at the moment but once I can test it out and it seems to not cause any issues I will merge.

**Comment by ColdHeat** [comment]
So I can see that the headers are installed. The following command shows the directory for the headers:

```
python -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'))"
```

Which returns:

```
root@35d95c8c483c:/usr/local/lib# python -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'))"
/usr/local/include/python3.7m
root@35d95c8c483c:/usr/local/lib# cd /usr/local/include/python3.7m
root@35d95c8c483c:/usr/local/include/python3.7m# ls
Python-ast.h	   bytes_methods.h  datetime.h		   floatobject.h  listobject.h	     node.h	    pgenheaders.h  pyexpat.h	  pystrcmp.h	  structseq.h	   weakrefobject.h
Python.h	   bytesobject.h    descrobject.h	   frameobject.h  longintrepr.h      object.h	    py_curses.h    pyfpe.h	  pystrhex.h	  symtable.h
abstract.h	   cellobject.h     dictobject.h	   funcobject.h   longobject.h	     objimpl.h	    pyarena.h	   pyhash.h	  pystrtod.h	  sysmodule.h
accu.h		   ceval.h	    dtoa.h		   genobject.h	  marshal.h	     odictobject.h  pyatomic.h	   pylifecycle.h  pythonrun.h	  token.h
asdl.h		   classobject.h    dynamic_annotations.h  graminit.h	  memoryobject.h     opcode.h	    pycapsule.h    pymacconfig.h  pythread.h	  traceback.h
ast.h		   code.h	    enumobject.h	   grammar.h	  metagrammar.h      osdefs.h	    pyconfig.h	   pymacro.h	  pytime.h	  tupleobject.h
bitset.h	   codecs.h	    errcode.h		   import.h	  methodobject.h     osmodule.h     pyctype.h	   pymath.h	  rangeobject.h   typeslots.h
bltinmodule.h	   compile.h	    eval.h		   internal	  modsupport.h	     parsetok.h     pydebug.h	   pymem.h	  setobject.h	  ucnhash.h
boolobject.h	   complexobject.h  fileobject.h	   intrcheck.h	  moduleobject.h     patchlevel.h   pydtrace.h	   pyport.h	  sliceobject.h   unicodeobject.h
bytearrayobject.h  context.h	    fileutils.h		   iterobject.h   namespaceobject.h  pgen.h	    pyerrors.h	   pystate.h	  structmember.h  warnings.h
```

**Comment by ColdHeat** [comment]
I'm reasonably confident that this is fine so I will merge and if in testing it results in issues I will revert it.

**Pull request merged**
