### PR TITLE
Unicode in filenames

### PR DESCRIPTION
**Pull request by rickest-rick**
Allow for challenge files to contain unicode characters. #1244

### CODE REVIEW

**Comment by ColdHeat** [comment]
Is this PR right? Doesn't seem to have any of your changes?

**Comment by rickest-rick** [comment]
I haven't committed anything - still trying to figure out where the issue is.

**Comment by rickest-rick** [comment]
>>> from werkzeug.utils import secure_filename
>>> secure_filename("😆")
''
>>> secure_filename("😆.lol")
'lol'

**Comment by rickest-rick** [comment]
I think you can remove this PR.  For my needs I'm going to patch werkzeug to allow that one unicode character, but it probably wouldn't be smart to enable unicode across the board for CTFd.

**Pull request closed without merging**
