### PR TITLE
Allow email modifications

### PR DESCRIPTION
**Pull request by jimender2**
This one should fix the issue I found in my previous pull request.

This works fine on my end but I encourage you to find ways to escape the formatting like it is shown here. https://www.palletsprojects.com/blog/jinja-281-released/
I hope this works for you, and I am considering if the from email address would be better suited to being on the email text page instead of its current location.

Should take care of #1002

### CODE REVIEW

**Comment by ColdHeat** [comment]
This should be able to make it into the next release if you want to rebase this against master. safe_format is already written to take care of the string format issue I believe.

**Comment by jimender2** [comment]
Ok, you will have to help me with that as I am still new to git.
From what I can tell I would checkout my branch, run git rebase master and then create a new pull request to the dev branch?

**Comment by ColdHeat** [comment]
I don't know the commands but you can target your PR to master. It's likely you can just do git rebase master.

**Comment by ColdHeat** [comment]
I created the 2.3.0-dev branch that can be used for this.

**Comment by ColdHeat** [comment]
This is pretty far removed from the 2.3.0-dev branch and I also have also improved some of the lint checks. The best option here is probably to resubmit this PR so you can get credit for in the contributors list.

**Comment by jimender2** [comment]
I was looking at all the merge conflicts and they were pretty high. I will rebuild the branch and submit a new request.

**Comment by ColdHeat** [comment]
@jimender2 You should be able to base things off of this branch: https://github.com/CTFd/CTFd/tree/1002-customizeable-outgoing-emails

I copied over the basic idea but haven't finished just yet.

**Comment by jimender2** [comment]
@ColdHeat Is there any difference between that branch and the 2.3.0-dev branch besides what you added in the rough outline?  I made a new branch based off of that branch and am currently testing it.  I plan to make a pull request based off of my copy that I already made in the morning assuming that there is no differences.

**Comment by ColdHeat** [comment]
@jimender2 you can see the comparison here: https://github.com/CTFd/CTFd/compare/2.3.0-dev...1002-customizeable-outgoing-emails?expand=1

The main difference is that it takes into account other changes that have been made.

**Pull request closed without merging**
