### PR TITLE
Add .gitattributes to keep .sh files with LF endings for Windows

### PR DESCRIPTION
**Pull request by Jus-Codin**
When trying to run CTFd on Windows using Docker Desktop, there is 2 issues that result in it being unable to run.

Some users might have Git configured to change line endings from LF to CRLF on checkout, resulting in Docker Desktop which runs the Docker Engine in WSL2 to be unable to interpret the line endings.

While it is possible to configure git to not auto-convert line endings, it would be better to specify to not change line endings for `.sh` and `.conf` files using `.gitattributes`, which would CTFd to run on Windows out of the box. Cheers to [this](https://github.com/CTFd/CTFd/issues/2598#issuecomment-2348927586) comment for identifying what was causing the issue.
  
Additionally, this PR also implements the [workaround](https://github.com/CTFd/CTFd/issues/2556#issuecomment-2293569821) for #2600. If this workaround is not ideal or a proper fix is identified, feel free to remove the changes made.

### CODE REVIEW

**Comment by ColdHeat** [comment]
I am against the migration change as I discussed in the related issue. If the migration needs to run, it should probably run and we should see what the underlying issue is. I feel that the issue is more related to MariaDB or WSL so I will likely remove the migration change. 

As for the line ending changes once I have the chance to verify this on Windows I will merge.

**Comment by Jus-Codin** [comment]
I found another fix for the migration issue in https://github.com/CTFd/CTFd/issues/2600#issuecomment-2365065037, lmk if it that fix is fine and I'll revert and add the fix accordingly

**Comment by Jus-Codin** [comment]
I've just reverted the migration issue workaround and swapped to the fix mentioned above, feel free to remove it if it is undesirable.

**Comment by ColdHeat** [comment]
On a fresh git clone (and also a zip download) I did not need to make any changes besides the volume change. I did not need to change the line endings. I was able to reproduce the bug though after manually changing the line endings. 

It looks like this is specific to users who have `git config --global core.autocrlf true` set. 

From my testing only the `.sh` file needs to be LF. And to get things working in Windows with WSL2 you do need to use one of the listed fixes. However, I really don't like the volume pattern personally.

**Comment by ColdHeat** [comment]
This issue also still appears to happen on more recent versions of MariaDB.

**Comment by ColdHeat** [comment]
From digging though this, the issue is MariaDB or WSL2's fault. This doesn't happen with `mysql:5.7`. 

CTFd shouldn't have to work around the lack of a proper `ALTER TABLE` functionality in the underlying database. 

I will accept the .gitattributes change but the volume change is something that needs to be worked out elsewhere. I will leave comments on the relevant issues to state that you need to change the volume to a dedicated volume.

**Pull request merged**
