### PR TITLE
Make ctfd user usable for mysql connection

### LINKED ISSUE #1027: Make db service in docker-compose use non-root user
**Environment**:

  - CTFd Version/Commit: b5632f9
  - Operating System: Docker v18.09.5
  - Web Browser and Version: not related

**What happened?**

```
Access denied for 'ctfd'@'%' to database 'ctfd'
```

**What did you expect to happen?**

Connect to CTFd database using ctfd user instead of using root.

**How to reproduce your issue**

```bash
docker-compose up -d
docker-compose logs -f
```

**Any associated stack traces or error logs**

```
ctfd_1   | [SQL: CREATE DATABASE ctfd CHARACTER SET = 'utf8mb4']
ctfd_1   | (Background on this error at: http://sqlalche.me/e/e3q8)
ctfd_1   | Waiting for db: to be ready
ctfd_1   | db is ready
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 8, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 137, in create_app
ctfd_1   |     url = create_database()
ctfd_1   |   File "/opt/CTFd/CTFd/utils/migrations/__init__.py", line 26, in create_database
ctfd_1   |     create_database_util(url, encoding="utf8mb4")
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 577, in create_database
ctfd_1   |     result_proxy = engine.execute(text)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
ctfd_1   |     return connection.execute(statement, *multiparams, **params)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
ctfd_1   |     return self._execute_text(object_, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1155, in _execute_text
ctfd_1   |     parameters,
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
ctfd_1   |     e, statement, parameters, cursor, context
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
ctfd_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
ctfd_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1044, u"Access denied for user 'ctfd'@'%' to database 'ctfd'")
ctfd_1   | [SQL: CREATE DATABASE ctfd CHARACTER SET = 'utf8mb4']
ctfd_1   | (Background on this error at: http://sqlalche.me/e/e3q8)
```

### PR DESCRIPTION
**Pull request by Creased**
Fix #1027 issue

### CODE REVIEW

**Comment by Creased** [comment]
Hey @ColdHeat what's the problem with Travis-CI? ([#2518](https://travis-ci.org/CTFd/CTFd/builds/547109348) passed)

**Comment by ColdHeat** [comment]
How does adding `MYSQL_DATABASE=ctfd` fix this issue? CTFd is responsible for creating the database because it sets some useful defaults in the database. 

I'm not sure this change is really worth it.

**Comment by Creased** [comment]
> 
> 
> How does adding `MYSQL_DATABASE=ctfd` fix this issue? CTFd is responsible for creating the database because it sets some useful defaults in the database.
> 
> I'm not sure this change is really worth it.

`MYSQL_DATABASE` is used by MariaDB container starting script to create a new empty database and grant permission to the ctfd user (as specified using the `MYSQL_USER` and `MYSQL_PASSWORD`).

Basically, both the `MYSQL_USER` and `MYSQL_PASSWORD` are unused since we're not using it for database connection and database creation.

**Comment by Creased** [comment]
CTFd concerns itself with creating the database because it needs to set the utf8mb4 default for proper unicode handling. Can you do this with docker-compose without using root?

_Originally posted by @ColdHeat in https://github.com/CTFd/CTFd/issues/1027#issuecomment-503389157_

As you mentioned in the #1027 issue, the database needs to be created using utf8mb4, I suggest defining this property using command entrypoint in `docker-compose.yml`.

**Comment by ColdHeat** [comment]
So this works correctly but if a user who is currently configured to connect with root and setup as root, will get an error that the ctfd user doesn't have access to the database.

**Comment by ColdHeat** [comment]
I think it's better to leave the DATABASE_URL as root for now. I don't want to have everyone who's using docker-compose need to add privileges to their database after an update.

I'd be more comfortable with that kind of change on a major release but right now I don't think the benefits outweigh the cost. Can you revert your DATABASE_URL change and I'll accept this?

**Comment by Creased** [comment]
Thanks @ColdHeat :)

**Pull request merged**
