### PR TITLE
use ruff instead of flake8

### PR DESCRIPTION
**Pull request by alperb**
I've removed `flake8` from dependencies and put `ruff` instead. Also replaced the command in `lint` part in the makefile.

In ruff, I wasn't able to find the equivalent rules for `W503` and `E203`. So I've removed these ignores from ruff as well. I've avoided using a `.ruff.toml` file for the configuration.

I haven't removed `flake8-isort` from `development.txt` in case it's used by `isort`. Unless it's used it can be removed too.

This PR resolves issue #2263

### CODE REVIEW

**Comment by ColdHeat** [comment]
Thanks for filing this. `flake8-isort` isn't used by isort. If you're removing `flake8` you can remove all of the other `flake8` plugins as well.

**Comment by ColdHeat** [comment]
I updated the PR to have the switches that I believe should cover the flake8 plugins and removed the extra flake8 plugins. If you could go through the new lints and either fix them if they're simple or simply ignore them.

**Comment by alperb** [comment]
3 rules were causing linting problems, `I001`, `B905` and `B904`. 

`I001` is "Import block is un-sorted or un-formatted".

`B904` is "Within an except clause, raise exceptions with raise ... from err or raise ... from None to distinguish them from errors in exception handling".

`B905` is "zip() without an explicit strict= parameter". 

I've ignored all of them, `I001` and `B904` were trivial. However, fixing `B905` may cause backward incompatible behaviors so I simply ignored it too, if you want it fixed I can, no problem.

**Comment by ColdHeat** [comment]
I think we can ignore B904 and B905 but I think for I001 can you ignore all the specific lines instead of ignoring it globally?

**Comment by alperb** [comment]
I've ignored `I001` on the lines which caused linting errors and enabled it globally on `make lint`. There were 32 lines :) So I've changed a lot of files. I think it's okay now.

**Pull request merged**
